modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL v2.1"
issueTrackerURL="https://github.com/BiggerSeries/BiggerUtilities/issues/" #optional

[[mods]] #mandatory
modId="biggerutilities" #mandatory
version="${version}" #mandatory
displayName="Bigger Utilities" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://biggerseries.net/" #optional
# logoFile="BiggerReactors.png" #optional
# A text field displayed in the mod UI
# credits="" #optional
# A text field displayed in the mod UI
authors="RogueLogix" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
'''

[[dependencies.biggerutilities]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[${forgeVersion},)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.biggerutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.biggerutilities]]
    modId="phosphophyllite"
    mandatory=true
    versionRange="${phosVersionRange}"
    ordering="NONE"
    side="BOTH"

